import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { GameClock, clockText, evaluationText, evaluationFill, INF } from '../web/clock.js';

const createChessBot = createRequire(import.meta.url)('../build/web/engine.js');
const engine = await createChessBot({ print() {}, printErr: console.error });
assert.equal(engine._cb_init(), 1);
const state = () => JSON.parse(engine.UTF8ToString(engine._cb_state()));
const load = fen => engine.ccall('cb_load', 'number', ['string'], [fen]);
const search = (time = 2500) => JSON.parse(engine.UTF8ToString(engine._cb_search(time, 0)));
const start = state().fen;
assert.equal(state().legal.length, 20);
assert.equal(engine._cb_move(12, 28, 5), 1);
assert.equal(engine._cb_move(12, 29, 5), 0);
assert.equal(engine._cb_undo(), 1);
assert.equal(state().fen, start);
assert.equal(engine._cb_redo(), 1);
const unchanged = state().fen;
assert.equal(load('8/8/8/8/8/8/8/8 w - - 0 1'), 0);
assert.equal(state().fen, unchanged);

assert.equal(load('r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1'), 1);
assert.equal(engine._cb_move(4, 6, 5), 1);
assert.match(state().fen, /R4RK1/);
assert.equal(engine._cb_undo(), 1);
assert.equal(load('7k/8/8/3pP3/8/8/8/7K w - d6 0 1'), 1);
assert.equal(engine._cb_move(36, 43, 5), 1);
assert.match(state().fen, /^7k\/8\/3P4\/8/);
assert.equal(load('7k/P7/8/8/8/8/8/7K w - - 0 1'), 1);
assert.equal(engine._cb_move(48, 56, 2), 1);
assert.match(state().fen, /^N6k/);

assert.equal(load(start), 1);
const beforeSearch = state().fen;
const normal = search();
assert.ok(state().legal.some(move => move.from === normal.move.from && move.to === normal.move.to));
assert.equal(state().fen, beforeSearch, 'Search must not mutate the game position');
assert.ok(normal.depth > 0);
assert.equal(load('7k/8/5KQ1/8/8/8/8/8 w - - 0 1'), 1);
const mate = search(5000);
assert.ok(mate.score >= INF - 64, `Expected a mate search score, received ${mate.score}`);
assert.equal(evaluationText(mate.score), '+M1');
assert.equal(load('7k/8/5K2/4Q3/8/8/8/8 w - - 0 1'), 1);
assert.equal(evaluationText(search(10000).score), '+M2', 'Actual search must report mate in two');
assert.equal(evaluationText(INF - 3), '+M2');
assert.equal(evaluationText(-INF + 4), '−M2');
assert.equal(evaluationFill(INF - 3), 100);
assert.equal(evaluationFill(-INF + 3), 0);
assert.equal(load('7k/6Q1/5K2/8/8/8/8/8 b - - 0 1'), 1);
assert.equal(state().result, 1);

const clock = new GameClock(300000, 5000);
clock.start(0, 0);
assert.deepEqual(clock.values(1250), [298750, 5000]);
assert.equal(clock.completeMove(0, 0, 1250), true);
assert.deepEqual(clock.values(1650), [298750, 4600]);
assert.equal(clock.completeMove(1, 100, 1650), true);
assert.deepEqual(clock.values(1650), [298750, 4700]);
clock.pause(2000);
assert.deepEqual(clock.values(9000), [298400, 4700]);
clock.reset(10, 5000); clock.start(0, 100);
assert.equal(clock.completeMove(0, 100, 110), false, 'Increment must not revive an expired clock');
assert.equal(clockText(5000), '00:05.0');
assert.equal(clockText(300000), '05:00');
console.log('WebAssembly integration, search mate telemetry and clock tests: PASS');
